### ISSUE TITLE
No versions available for pelicanjs

### ISSUE THREAD

**Issue by DjovDev** [timothyverhaeghe/pelicanjs#1]
Hello
I inherited a project using the pelicanJS library

When installing the project, I get the following:

```
> npm install pelicanjs
npm ERR! code ENOVERSIONS
npm ERR! No versions available for pelicanjs
```
Has pelicanjs been removed from NPM?

**Comment by timothyverhaeghe** [comment]
It was a library I only used for a few internal projects several years ago. While cleaning up my NPM (to get some more structure), I removed this package.

I suggest that you replace the PelicanJS functions with the functions directly in the Github repository OR that you take the index.js file and put that file in a folder somewhere (and load it from there).
